### ISSUE TITLE
import CModbus -> No such module

### ISSUE THREAD

**Issue by poffel1976** [DimaRU/SwiftyModbus#1]
Hey,

i wanted to use this lib in my Project, but i can't figure out what i am missing. It's always complaining about "import CModbus -> No such module"
Any help would be really appreciated. ;-)

**Comment by DimaRU** [comment]
Hi! CModbus used only internally for import libmodbus symbols. Try 
```swift
import SwiftyModbus
```
or
```swift
import SwiftyModbusPromise
```

Please use [https://github.com/DimaRU/SampleSwiftyModbus](https://github.com/DimaRU/SampleSwiftyModbus) for samples.

**Comment by poffel1976** [comment]
The error occurs in SwiftyModbusPromise.swift, SwiftyModbus.swift and SwiftyModbusResult.swift. I am only importing SwiftyModbusPromise.

**Comment by DimaRU** [comment]
Although for an accurate answer much more information is needed (such as the name and version of the operating system, libmodbus version, Swift or Xcode version, build logs), I guess that libmodbus needs to be installed.
```bash
brew install libmodbus
```
or
```bash
apt install libmodbus-dev
```

**Comment by poffel1976** [comment]
Thanks a lot! For some reason i need to reinstall libmodbus. Your hint helped me. Thanks again.
Are you planning to support iOS also?

**Comment by DimaRU** [comment]
> Thanks a lot! For some reason i need to reinstall libmodbus. Your hint helped me. Thanks again. Are you planning to support iOS also?

Itself SwiftyModbus library is os-agnostic. You will need to compile libmodbus for iOS. It's not difficult. For example see [https://github.com/DimaRU/FastDDSPrebuild](https://github.com/DimaRU/FastDDSPrebuild ). But I don't see a real use case of controlling an industrial device with an iPhone.
I use SwiftyModbus to control industrial equipment on NVidia Jetson platform under Linux.
